--Voluntario
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.555.124-1','Gustaco Fernandez','Atacama','Freirina','956755214','1998-06-12','correo1@gmail.com',true,true,true,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.354.785-3','Andrea Fernandez','La Serena','Vallenar','989654125','1996-05-06','correo2@gmail.com',false,false,true,false,true,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.534.485-6','Ariel Urra','Arica y Parinacota','Arica','956515345','1998-08-01','correo3@gmail.com',true,false,true,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.254.534-7','Fernando Gonzalez','OHiggins','Rancagua','921235651','1995-07-27','correo4@gmail.com',true,true,true,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.454.754-8','Andrea Donoso','Los Rios','Valdivia','988652255','1998-09-28','correo5@gmail.com',true,false,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.123.454-6','Chantal Moreno','Metropolitana','Santiago','942165621','1998-02-10','correo6@gmail.com',true,true,true,true,true,false,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.568.445-2','Ybraim Huenchumilla','Araucania','Temuco','974851263','1997-03-10','correo7@gmail.com',true,true,true,true,true,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.124.343-3','Jorge Sepulveda','Metropolitana','Santiago','912548613','1995-04-03','correo8@gmail.com',false,false,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.324.435-3','Fabian Contreras','Arica y Parinacota','Arica','914625375','1993-04-02','correo9@gmail.com',true,false,true,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.464.324-5','Hugo Guerrero.','Atacama','Tierra Amarilla','926563546','1985-01-15','correo10@gmail.com',true,true,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.678.451-6','Felipe Aravena','Tarapaca','Iquique','955676356','1985-01-13','correo11@gmail.com',true,true,false,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('16.135.543-2','Javier Nova','Coquimbo','Ovalle','965846254','1980-10-27','correo12@gmail.com',false,false,false,true,false,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.467.123-2','Alexis Gutierrez','Valparaiso','Panquehue','926868843','1994-03-09','correo13@gmail.com',true,false,true,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.651.577-7','Javier Carvajal','Ohiggins','Palmilla','917658431','1986-07-27','correo14@gmail.com',true,true,true,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.765.432-5','Hugo Arriaza','Ohiggins','Requinoa','913336783','1983-07-31','correo15@gmail.com',false,false,true,true,false,false,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.435.543-4','Ariel Lagos','Maule','Parral','914333323','1996-04-06','correo16@gmail.com',false,false,true,true,true,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.987.765-2','Carlos Aravena','Maule','Pencahue','912414341','1990-11-14','correo17@gmail.com',true,false,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.153.234-9','Jean Sepulveda','Biobio','Negrete','935573337','1992-05-21','correo18@gmail.com',false,false,true,true,true,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.562.765-7','Alberto Duran','Araucania','Freire','935733434','1998-11-30','correo19@gmail.com',true,false,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.576.654-6','Carlos Arriaza','Biobio','Yumbel','954563343','1990-11-06','correo20@gmail.com',true,false,true,true,true,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.573.334-4','Alexander Duran','Atacama','Chañaral','953443654','1980-05-26','correo21@gmail.com',false,false,true,true,false,false,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.456.755-3','Fabian Zarate','Araucania','Temuco','935346655','1994-05-15','correo22@gmail.com',false,false,true,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.555.435-6','Alexis Zuniga','Los Rios','Paillaco','954564575','1985-04-21','correo23@gmail.com',true,true,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.512.256-8','Diego Sanchez','Biobio','Antuco','955154533','1996-01-30','correo24@gmail.com',true,false,true,true,true,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.587.755-5','Nelson Carvajal','Los Rios','Valdivia','993456745','1987-06-01','correo25@gmail.com',true,false,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.134.885-1','Jean Pizarro','Los Lagos','Puyehue','917536632','1995-02-04','correo26@gmail.com',true,true,true,true,true,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.564.233-4','Alberto Diaz','Magallanes','Porvenir','956867356','1999-12-02','correo27@gmail.com',true,true,true,true,false,false,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.876.774-1','Ricardo Duran','Los Lagos','Puerto Montt','922356547','1996-09-03','correo28@gmail.com',false,false,true,true,true,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.434.256-1','Ricardo Zarate','Magallanes','San Gregorio','976786333','1987-11-20','correo29@gmail.com',true,true,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.974.232-5','Antonio Torres','Ohiggins','Rancagua','967878534','1995-01-14','correo30@gmail.com',true,false,false,true,true,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.244.243-4','Diego Zarate B.','Arica y Parinacota','Camarones','951576563','1999-09-27','correo31@gmail.com',true,true,true,true,true,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.775.264-3','Daniel Guerrero','Tarapaca','Colchane','976864353','1996-08-19','correo32@gmail.com',true,false,false,true,false,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.564.845-3','David Zuniga','Antofagasta','Calama','956584565','1993-04-24','correo33@gmail.com',true,true,true,false,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.355.365-6','Nelson Sanchez','Atacama','Huasco','954626365','1980-04-05','correo34@gmail.com',true,false,true,true,true,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.224.836-8','David Arriaza','Atacama','Caldera','933145334','1981-11-29','correo35@gmail.com',true,true,true,true,false,false,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.865.284-9','Felipe Duran','Antofagasta','Sierra Gorda','924358666','1981-10-02','correo36@gmail.com',true,false,false,true,true,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.246.843-3','Felipe Nova','Arica y Parinacota','Putre','924362432','1996-06-18','correo37@gmail.com',true,false,true,true,true,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.654.846-4','Hugo Gutierrez','Coquimbo','Illapel','924655874','1999-04-16','correo38@gmail.com',true,false,true,true,false,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.246.354-7','Ariel Orostica','Araucania','Cholchol','921345665','1992-10-08','correo39@gmail.com',true,false,true,false,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('19.573.754-3','Pepe Diaz','Metropolitana','Cerrillos','967654533','1987-11-06','correo40@gmail.com',false,false,true,true,false,false,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.683.454-5','Fabian Torres','Antofagasta','Mejillones','943658525','1999-12-18','correo41@gmail.com',true,false,true,true,false,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.243.654-8','Luciano Pizarro','Coquimbo','Paihuano','946563525','1992-09-16','correo42@gmail.com',false,false,true,true,false,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.974.652-5','Diego Guerrero','Metropolitana','Macul','986514235','1997-10-06','correo43@gmail.com',true,true,true,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('16.254.353-2','Carlos Torres','Ohiggins','Rengo','923455774','1994-11-01','correo44@gmail.com',true,false,true,false,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.456.122-4','Ariel Fuentes','Tarapaca','Huara','987657342','1989-07-18','correo45@gmail.com',true,false,true,true,false,false,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.765.114-6','Nelson Espinoza','Maule','Yerbas Buenas','978564324','1986-07-18','correo46@gmail.com',true,false,false,false,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.352.126-8','Alexander Sepulveda','Metropolitana','Providencia','923456754','1989-09-08','correo47@gmail.com',true,false,false,true,false,true,false);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('18.245.124-7','Luciano Gutierrez','Biobio','Talcahuano','985676245','1987-06-12','correo48@gmail.com',true,false,true,true,true,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.643.132-3','Jose Faundez','Ohiggins','Quinta de Tilcoco','934513434','1989-04-25','correo49@gmail.com',true,false,false,true,false,true,true);
INSERT INTO "Voluntario"(rut,nombre,region,ciudad,telefono_contacto,fecha_nacimiento,correo,disponibilidad_lunes,disponibilidad_martes,disponibilidad_miercoles,disponibilidad_jueves,disponibilidad_viernes,disponibilidad_sabado,disponibilidad_domingo) VALUES('17.324.135-9','Luis Diaz','Metropolitana','Puente Alto','987583562','1988-07-03','correo50@gmail.com',true,false,true,true,false,false,false);

--Instituciones
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_1','descripcion_1');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_2','descripcion_2');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_3','descripcion_3');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_4','descripcion_4');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_5','descripcion_5');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_6','descripcion_6');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_7','descripcion_7');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_8','descripcion_8');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_9','descripcion_9');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_10','descripcion_10');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_11','descripcion_11');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_12','descripcion_12');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_13','descripcion_13');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_14','descripcion_14');
INSERT INTO "Institucion"(nombre,descripcion) VALUES('Institucion_15','descripcion_15');

--Habilidad
INSERT INTO "Habilidad"(criterio) VALUES('criterio_1');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_2');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_3');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_4');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_5');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_6');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_7');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_8');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_9');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_10');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_11');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_12');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_13');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_14');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_15');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_16');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_17');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_18');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_19');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_20');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_21');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_22');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_23');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_24');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_25');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_26');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_27');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_28');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_29');
INSERT INTO "Habilidad"(criterio) VALUES('criterio_30');

--Emergencia

INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(1,'Emergencia 1','Grave','descripcion_1','nombre_coor_1','rut_coor_1','correo_coor_1','Santiago','Metropolitana');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(2,'Emergencia 2','Agudo','descripcion_2','nombre_coor_2','rut_coor_2','correo_coor_2','Rancagua','Ohiggins');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(3,'Emergencia 3','Peligroso','descripcion_3','nombre_coor_3','rut_coor_3','correo_coor_3','Santiago','Metropolitana');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(4,'Emergencia 4','Grave','descripcion_4','nombre_coor_4','rut_coor_4','correo_coor_4','Temuco','Araucania');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(9,'Emergencia 5','Grave','descripcion_5','nombre_coor_5','rut_coor_5','correo_coor_5','Nueva Imperial','Araucania');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(6,'Emergencia 6','Agudo','descripcion_6','nombre_coor_6','rut_coor_6','correo_coor_6','Concepcion','Biobio');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(7,'Emergencia 7','Grave','descripcion_7','nombre_coor_7','rut_coor_7','correo_coor_7','Temuco','Araucania');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(2,'Emergencia 8','Grave','descripcion_8','nombre_coor_8','rut_coor_8','correo_coor_8','Santiago','Metropolitana');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(4,'Emergencia 9','Grave','descripcion_9','nombre_coor_9','rut_coor_9','correo_coor_9','Valdivia','Los Rios');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(5,'Emergencia 10','Agudo','descripcion_10','nombre_coor_10','rut_coor_10','correo_coor_10','Pichilemu','Ohiggins');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(7,'Emergencia 11','Peligroso','descripcion_11','nombre_coor_11','rut_coor_11','correo_coor_11','San Bernardo','Metropolitana');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(2,'Emergencia 12','Agudo','descripcion_12','nombre_coor_12','rut_coor_12','correo_coor_12','Punta Arenas','Magallanes');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(8,'Emergencia 13','Grave','descripcion_13','nombre_coor_13','rut_coor_13','correo_coor_13','Antofagasta','Antofagasta');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(2,'Emergencia 14','Peligroso','descripcion_14','nombre_coor_14','rut_coor_14','correo_coor_14','Melipilla','Metropolitana');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(7,'Emergencia 15','Agudo','descripcion_15','nombre_coor_15','rut_coor_15','correo_coor_15','Tocopilla','Antofagasta');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(10,'Emergencia 16','Agudo','descripcion_16','nombre_coor_16','rut_coor_16','correo_coor_16','Ovalle','Coquimbo');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(11,'Emergencia 17','Grave','descripcion_17','nombre_coor_17','rut_coor_17','correo_coor_17','Putre','Arica y Parinacota');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(4,'Emergencia 18','Peligroso','descripcion_18','nombre_coor_18','rut_coor_18','correo_coor_18','Pozo Almonte','Tarapaca');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(12,'Emergencia 19','Peligroso','descripcion_19','nombre_coor_19','rut_coor_19','correo_coor_19','Calama','Antofagasta');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(13,'Emergencia 20','Agudo','descripcion_20','nombre_coor_20','rut_coor_20','correo_coor_20','Illapel','Coquimbo');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(1,'Emergencia 21','Grave','descripcion_21','nombre_coor_21','rut_coor_21','correo_coor_21','Quillota','Valparaiso');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(14,'Emergencia 22','Grave','descripcion_22','nombre_coor_22','rut_coor_22','correo_coor_22','Puerto Montt','Los Lagos');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(9,'Emergencia 23','Agudo','descripcion_23','nombre_coor_23','rut_coor_23','correo_coor_23','Rancagua','Ohiggins');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(10,'Emergencia 24','Grave','descripcion_24','nombre_coor_24','rut_coor_24','correo_coor_24','Talca','Maule');
INSERT INTO "Emergencia"(institucion_encargada,nombre_emergencia,estado_emergencia,descripcion,nombre_coordinador,rut_coordinador,correo_coordinador,ciudad,region) VALUES(15,'Emergencia 25','Peligroso','descripcion_25','nombre_coor_25','rut_coor_25','correo_coor_25','San Felipe','Valparaiso');

--Tarea
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(1,'Terminada','nombre_1','descripcion_1',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(2,'En proceso','nombre_2','descripcion_2',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(3,'No iniciada','nombre_3','descripcion_3',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(4,'No iniciada','nombre_4','descripcion_4',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(5,'En proceso','nombre_5','descripcion_5',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(6,'En proceso','nombre_6','descripcion_6',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(7,'En proceso','nombre_7','descripcion_7',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(3,'Terminada','nombre_8','descripcion_8',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(4,'Terminada','nombre_9','descripcion_9',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(4,'No iniciada','nombre_10','descripcion_10',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(8,'En proceso','nombre_11','descripcion_11',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(1,'Terminada','nombre_12','descripcion_12',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(3,'Terminada','nombre_13','descripcion_13',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(8,'No iniciada','nombre_14','descripcion_14',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(10,'En proceso','nombre_15','descripcion_15',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(11,'No iniciada','nombre_16','descripcion_16',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(15,'Terminada','nombre_17','descripcion_17',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(13,'En proceso','nombre_18','descripcion_18',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(8,'Terminada','nombre_19','descripcion_19',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(3,'No iniciada','nombre_20','descripcion_20',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(4,'En proceso','nombre_21','descripcion_21',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(10,'No iniciada','nombre_22','descripcion_22',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(14,'Terminada','nombre_23','descripcion_23',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(12,'En proceso','nombre_24','descripcion_24',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(12,'No iniciada','nombre_25','descripcion_25',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(4,'No iniciada','nombre_26','descripcion_26',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(2,'En proceso','nombre_27','descripcion_27',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(1,'En proceso','nombre_28','descripcion_28',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(9,'En proceso','nombre_29','descripcion_29',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(7,'Terminada','nombre_30','descripcion_30',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(6,'Terminada','nombre_31','descripcion_31',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(5,'No iniciada','nombre_32','descripcion_32',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(4,'En proceso','nombre_33','descripcion_33',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(11,'Terminada','nombre_34','descripcion_34',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(12,'Terminada','nombre_35','descripcion_35',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(9,'No iniciada','nombre_36','descripcion_36',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(2,'En proceso','nombre_37','descripcion_37',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(6,'En proceso','nombre_38','descripcion_38',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(3,'Terminada','nombre_39','descripcion_39',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(2,'En proceso','nombre_40','descripcion_40',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(7,'Terminada','nombre_41','descripcion_41',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(15,'No iniciada','nombre_42','descripcion_42',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(14,'En proceso','nombre_43','descripcion_43',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(13,'No iniciada','nombre_44','descripcion_44',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(2,'Terminada','nombre_45','descripcion_45',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(10,'No iniciada','nombre_46','descripcion_46',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(9,'En proceso','nombre_47','descripcion_47',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(4,'En proceso','nombre_48','descripcion_48',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(8,'Terminada','nombre_49','descripcion_49',5);
INSERT INTO "Tarea"(emergencia,estado_tarea,nombre,descripcion,voluntarios_requeridos) VALUES(2,'En proceso','nombre_50','descripcion_50',5);

--Ranking se pobla solo a traves del procedimiento almacenado


--Emergencia_Habilidad

INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,27);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(22,21);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(16,10);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(2,4);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(14,2);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(20,21);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(7,2);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(22,3);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(17,12);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(14,11);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(10,22);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(16,7);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(2,29);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(18,9);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(10,20);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(1,11);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(1,2);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(8,1);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(2,12);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(23,25);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(15,27);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(6,22);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(1,3);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(1,5);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(3,22);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(22,26);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,29);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(18,29);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(21,4);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(1,19);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(24,26);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(12,14);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(12,18);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(2,27);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(6,18);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(16,21);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,27);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(16,15);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(24,13);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(7,23);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,1);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(21,9);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(21,28);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(14,10);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(20,1);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(24,22);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(10,11);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(4,9);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(22,27);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(7,21);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,14);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(14,6);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(10,13);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(6,5);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(14,26);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(2,15);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(19,10);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(8,5);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(13,14);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(16,10);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(17,7);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(24,21);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(12,27);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(15,13);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,2);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(17,18);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(7,12);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(13,3);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(9,1);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(1,26);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(19,20);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(8,13);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(4,23);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(14,10);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(11,24);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(14,10);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(18,8);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(19,27);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,17);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(1,22);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(23,21);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(17,5);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,6);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(1,15);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(8,13);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(10,6);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(24,9);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(18,13);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(10,12);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(19,3);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(22,3);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(2,18);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,10);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(20,23);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(21,19);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,29);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(7,14);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(15,11);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(5,8);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(6,12);
INSERT INTO "Emergencia_Habilidad"(id_emergencia,id_habilidad) VALUES(6,24);

--Tarea_habilidad

INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(40,7);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(9,4);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(32,19);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(34,25);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(11,19);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(23,19);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(16,23);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(18,17);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(11,9);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(40,21);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(10,22);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(35,11);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(42,8);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(44,18);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(43,11);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(28,17);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(5,21);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(31,30);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(24,30);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(35,8);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(27,10);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(44,15);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(28,28);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(37,6);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(25,2);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(10,23);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(6,3);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(35,9);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(1,4);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(47,27);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(16,4);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(8,8);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(21,22);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(26,29);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(12,24);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(31,15);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(17,19);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(19,8);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(1,3);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(41,9);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(13,11);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(38,24);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(37,24);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(7,23);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(40,2);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(11,6);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(40,29);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(14,4);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(30,26);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(46,11);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(30,25);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(39,15);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(47,11);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(18,8);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(26,1);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(33,14);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(25,29);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(36,26);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(16,16);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(42,21);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(41,25);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(49,29);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(45,7);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(14,11);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(19,20);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(31,26);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(44,7);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(12,23);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(39,28);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(12,9);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(4,21);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(45,10);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(30,9);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(26,3);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(33,8);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(47,5);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(34,6);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(18,15);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(47,25);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(34,8);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(12,8);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(27,21);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(47,20);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(42,21);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(44,1);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(36,28);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(18,22);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(35,7);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(44,17);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(31,24);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(10,6);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(7,24);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(3,27);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(46,10);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(12,26);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(29,26);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(45,15);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(44,17);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(6,18);
INSERT INTO "Tarea_Habilidad"(id_tarea,id_habilidad) VALUES(12,14);


--Voluntario_habilidad



INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(2,27);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(15,28);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(18,10);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(32,25);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(37,2);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(13,17);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(19,5);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(2,16);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(49,30);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(38,9);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(40,23);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(13,30);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(43,6);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(22,24);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(21,12);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(42,20);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(39,6);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(11,30);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(46,6);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(26,27);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(11,28);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(27,11);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(25,9);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(37,18);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(6,14);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(2,3);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(42,26);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(21,19);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(48,30);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(9,26);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(2,2);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(14,13);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(40,28);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(32,16);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(15,25);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(20,10);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(28,19);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(39,8);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(2,13);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(34,29);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(20,20);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(7,6);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(36,28);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(49,14);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(15,4);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(10,11);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(3,11);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(14,24);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(19,11);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(5,13);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(36,20);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(42,17);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(43,6);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(16,29);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(10,28);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(31,15);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(22,29);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(4,22);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(5,2);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(37,16);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(26,11);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(43,18);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(30,4);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(5,21);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(21,15);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(18,7);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(43,10);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(41,6);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(35,6);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(27,13);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(11,17);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(20,24);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(1,24);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(40,9);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(29,14);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(24,5);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(4,2);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(8,19);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(48,24);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(24,27);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(2,20);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(13,8);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(14,21);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(39,24);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(50,28);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(41,27);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(9,14);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(21,22);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(23,3);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(27,3);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(50,20);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(33,17);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(24,21);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(46,26);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(48,25);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(43,27);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(31,16);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(16,18);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(4,6);
INSERT INTO "Voluntario_Habilidad"(id_voluntario,id_habilidad) VALUES(13,10);